# -*- coding: utf-8 -*-
"""py3dmol.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LD1awcaE_8J5n92UJMSQRF-UQGtrfRqF

## Visualisation of molecules like protein from RCSB PDB using their PDB ID and molecule(ligand) from PubChem Database uding their Compound ID

IN THIS TUTORIAL WE HAVE VISUALIZE compound Nirmatrelvir (Paxlovid)  and protein Main Protease M^pro of SARS-CoV-2
"""

pip install py3Dmol

"""This little command sets up our notebook by installing the `py3Dmol` library. Think of `py3Dmol` as a special tool that lets us see and play with 3D models of molecules right here in our notebook!"""

!pip install py3Dmol
!pip install nglview

"""Here, we're just double-checking that both `py3Dmol` (our 3D molecule viewer) and `nglview` (another great tool for looking at molecules) are installed and ready to go. It's like making sure all your art supplies are present before you start drawing!"""

import py3Dmol
ibux = py3Dmol.view(query='cid:155903259')
ibux.setStyle({'stick': {'color': 'spectrum'}})

"""In this cell, we're telling `py3Dmol` to grab the structure of Ibuprofen for us! We're using its special PubChem ID (`155903259`) to find it. Then, we tell it to draw the molecule as 'sticks' and color it in a lovely 'spectrum' of colors based on the different types of atoms."""

import py3Dmol

ibux = py3Dmol.view(query='cid:155903259')
ibux.setStyle({'stick': {'color': 'spectrum'}})
ibux.addSurface('VDw', opacity=0.5, colorScheme=('gradient','rwd'))

"""Building on the last step, we're again showing Ibuprofen as 'sticks' with pretty 'spectrum' colors. But this time, we're also adding a transparent 'surface' around it, like a bubbly force field, to show its overall shape and how much space it takes up. The colors on this surface fade from red to white to blue."""

Mpro = py3Dmol.view(query='pdb:7RFS')
Mpro.setStyle({'cartoon': {'color': 'spectrum'}})

"""Now we're moving on to a protein! This code fetches the structure of protein namely Main Protease (Mpro) of SARS-CoV-2 using its PDB ID (`7RFS`). We're telling it to draw the protein in a 'cartoon' style, which is super helpful for seeing its main structural features like spirals and ribbons, again with those vibrant 'spectrum' colors."""

Mpro = py3Dmol.view(query='pdb:7RFS')
Mpro.setStyle({'cartoon': {'color': 'spectrum'}})
Mpro.addSurface('VDw', opacity=0.1, colorScheme=('gradient','rwd'))

"""Finally, we're looking at that Celecoxib protein again in its 'cartoon' glory, but we're adding a very subtle, transparent surface this time (only 10% opaque). This lets us still clearly see the cool cartoon structure underneath while getting a hint of the protein's overall boundary, using the same red-white-blue gradient colors."""